name: Build

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn test
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
      - name: Coverage client
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          working-directory: client
      - name: Coverage server
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          working-directory: server
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          COOKIE_SECRET: ${{ secrets.AZURE_CLIENT_ID }}
